---
title: "Informacje ogólne"
---

## Analiza danych w czasie rzeczywistym

Kod: 222890-D

Semestr letni 2024,
SGH Szkoła Główna Handlowa w Warszawie

Podstawowe informacje znajdziesz w [sylabusie](/RTA_2024/sylabus).

Ciekawe książki i strony internetowe zamieszczone zostały w zakładce [książki](/RTA_2024/ksiazki). Jeśli chciał(a)byś coś dodać prześlij informację przez MS teams.

## Kalendarz

#### Wykład 

Wykład jest realizowany w trybie stacjonarnym.
Jest on NIEOBOWIĄZKOWY i odbywa się w Auli II bud G

1. 26-02-2024 (poniedziałek) 09:50-11:30 - Wykład 1
Tematy zrealizowane na wykładzie:
    - Dane ustrukturyzowane i nieustrukturyzowane
    - Procesy generowania danych
    - Big Data
    - Modele przetwarzania danych OLTP, OLAP

2. 04-03-2024 (poniedziałek) 09:50-11:30 - Wykład 2
Tematy zrealizowane na wykładzie:
    - Przetwarzanie wsadowe vs Przetwarzanie strumieni danych
    - ETL 
    - Wzorzec MapReduce
    - Biznesowe wymagania dla strumieni danych
    - Definicje: Zdarzenie, strumień zdarzeń, analiza i przetwarzanie strumieni zdarzeń, 
    - Narzędzie i aplikacje przetwarzania strumieniowego

3. 11-03-2024 (poniedziałek) 09:50-11:30 - Wykład 3
Tematy reazlizowane na wykładzie: 
    - Czas w przetwarzaniu danych strumieniowych  
    - Działanie systemu klient-serwer: REST API
4. 18-03-2024 (poniedziałek) 09:50-11:30 - Wykład 4
Tematy realizowane na wykładzie:
    - TEST 20 pytań!
    - Działanie systemu pub-sub: Apache Kafka
    - Architektura Lammbda i Kappa

5. 25-03-2024 (poniedziałek) 09:50-11:30 - Wykład 5
Tematy realizowane na wykładzie:
    - TEST 20 pytań! - 30 minut.
    - Przygotowanie środowiska pracy
    
Test przeprowadzany jest za pośrednictwem MS Teams.

#### Laboratoria

1. 08-04-2024 (poniedziałek) 08:00-13:20 - C1A 3 grupy 
1. 09-04-2024 (wtorek) 09:50-17:00 - C2B 3 grupy 

2. 15-04-2024 (poniedziałek) 08:00-13:30 - C1A, 3 grupy 
2. 16-04-2024 (wtorek) 09:50-17:00 - C2B, 3 grupy 

3. 22-04-2024 (poniedziałek) 08:00-13:30 - C1A, 3 grupy
3. 23-04-2024 (wtorek) 09:50-17:00 - C2B, 3 grupy 

4. 29-04-2024 (poniedziałek) 08:00-13:30 - C1A, 3 grupy 
4. 30-04-2024 (wtorek) 09:50-17:00 - C2B, 3 grupy 

5. 06-05-2024 (poniedziałek) 08:00-13:30 - C1A, 3 grupy
5. 07-05-2024 (wtorek) 09:50-17:00 - C2B, 3 grupy 

6. 13-05-2024 (poniedziałek) 08:00-13:30 - C2B, 3 grupy
6. 14-05-2024 (wtorek) 09:50-17:00 - C2B, 3 grupy 

7. 20-05-2024 (poniedziałek) 08:00-13:30 - C2B, 3 grupy
7. 21-05-2024 (wtorek) 09:50-17:00 - C2B, 3 grupy

8. 27-05-2024 (poniedziałek) 08:00-13:30 - C2B, 3 grupy
8. 28-05-2024 (wtorek) 09:50-17:00 - C2B, 3 grupy 

9. 03-06-2024 (poniedziałek) 08:00-13:30 - C2B, 3 grupy
9. 04-06-2024 (wtorek) 11:40-17:00 - C2B, 3 grupy
- Apache Kafka i Apache Spark Streaming



<!-- 
W przyszłym roku zrobić na ostatnich zajęciach test z ćwiczeń. 

Jako 90 minutowe zadania do realizacji w notatniku.
Przedstawiający krok po kroku 
- Przygotowanie danych dla szeregu czasowego 
- skrypt w pythonie wysyłający dane do Apache Kafka
- skrypt w pythonie lub Apache Spark odbierający dane z Apache Kafka 
- obliczenie średniej w oknie i wypisanie wyniku na ekran 
- gdy wartość > x to zapis do mongodb (to musi być na ćwiczeniach)
- wizualizacja danych w pythonie z podłączenia mongodb - ile razy pojawia się przekrocznie - to też na ćwiczeniach
-->

#### Miejsce

Wykłady 1-5: G-Aula II
Laboratorium 1-9: C1A, C2B

#### Zaliczenie i Egzamin

Wykłady zakończone zostaną testem (ostatnie zajęcia).
Pozytywna ocena z testu (powyżej 13 pkt) upoważnia do realizacji ćwiczeń. 

Po ćwiczeniach realizowane będą zadania domowe przekazywane za pośrednictwem platformy teams.  
Zaliczenie wszystkich ćwiczeń i zadań upoważnia do realizacji projektu. 

Projekt powinien być realizowany w grupach max 5 osobowych. 

Wymagania projektu: 

- Projekt powinien przedstawiać BIZNESOWY PROBLEM, który można realizować wykorzystując informacje podawane w trybie online. (Nie oznacza to, że nie można korzystać z procesowania batchowego np w celu wygenerowania modelu).
- Dane powinny być przesyłane do Apache Kafki i stamtąd poddawane dalszemu procesowaniu i analizie. 
- Język programowania jest dowolny - dotyczy każdego komponentu projektu. 
- Można wykorzystać narzędzia BI 
- Źródłem danych może być tabela, sztucznie generowane dane, IoT itp.

## Technologie

Uczestnicząc w zajęciach musisz opanować i przynajmniej w podstawowym zakresie posługiwać się następującymi technologiami informatycznymi:

1. [GIT](https://sebkaz-teaching.github.io/RTA_2023/info.html#git) 
2. Python, Jupyter notebook, Jupyter lab, Colab
3. [Docker](https://sebkaz-teaching.github.io/RTA_2023/info.html#docker)
4. **Apache Spark**, Apache Flink, **Apache Kafka**, Apache Beam
5. Databricks Community edition [Web page](https://community.cloud.databricks.com/login.html).